version: '3.8'

services:
  db:
    image: mysql:8.0 
    container_name: reservation-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservation-mysql
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    ports:
      - "3306:3306" 
    networks:
      - spring-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  meal-service:
    build: ./meal-service
    container_name: meal-service
    ports:
      - "8881:8881"
    networks:
      - spring-network    

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: reservation-app
    ports:
      - "8889:8888"   
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      MEAL_HOST: meal-service
      DB_HOST: db
      SPRING_DATASOURCE_USERNAME: spring 
      SPRING_DATASOURCE_PASSWORD: spring
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge

volumes:
  mysql_data: