
services:
  db:
    image: mysql:8.0 
    container_name: reservation-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservation-mysql
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    ports:
      - "3306:3306" 
    networks:
      - spring-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  meal-service:
    build: ./meal-service
    container_name: meal-service
    ports:
      - "8882:8881"
    environment:
      - EUREKA_HOST=eureka-server
      - ZIPKIN_HOST=zipkin
      - DB_HOST=db
    networks:
      - spring-network    
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
      zipkin:
        condition: service_started

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - spring-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - spring-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - spring-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports: 
      - "8761:8761"
    networks:
      - spring-network    

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_HOST=eureka-server
      - ZIPKIN_HOST=zipkin
    networks:
      - spring-network
    depends_on:
      - eureka-server
      - zipkin

  app:
    build: .
    deploy:
      replicas: 3
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      EUREKA_HOST: eureka-server
      MEAL_HOST: meal-service
      ZIPKIN_HOST: zipkin
      DB_HOST: db
      SPRING_DATASOURCE_USERNAME: spring 
      SPRING_DATASOURCE_PASSWORD: spring
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - spring-network
    
networks:
  spring-network:
    driver: bridge

volumes:
  mysql_data:
  rabbitmq_data:

