spring.application.name=programski-jezici
spring.datasource.url=jdbc:mysql://localhost:3309/takmicenje
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
meal.api.base-url=https://www.themealdb.com/api/json/v1/1
# movie.api.name-header=PJ_2026
# 1. Uključivanje kompresije na serveru
server.compression.enabled=true
# 2. Tipovi podataka koje želimo da kompresujemo 
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
# 3. Minimalna veličina odgovora (u bajtovima) za koju se isplati raditi kompresiju ~0.5KB
server.compression.min-response-size=500
server.port=8888
# server.error.include-message=always
# logging.level.org.hibernate.SQL=DEBUG

# 1. Grupisanje više INSERT/UPDATE upita u jedan paket (za rad sa listama)
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# 2. Vraćanje konekcije u bazen čim se pročitaju podaci sa baze (brže oslobađanje resursa)
spring.jpa.open-in-view=false

# 3. HikariCP - održavanje otvorenih konekcija ka bazi
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
yelp.api.key=v5WJWkERrK2Q_qv4mXvGdIcByb-_tLLgHcaMrm38RhPFnSjVSO3b0-HmqY0eZBT_tvpJPPe46BFOBknEY0e18jmW55OAVABogqypM1iZcgmT0X2U_Aw0_rRaXmJvanYx