spring.application.name=programski-jezici
spring.datasource.url=jdbc:mysql://localhost:3309/takmicenje
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
# 1. Uključivanje kompresije na serveru
server.compression.enabled=true
# 2. Tipovi podataka koje želimo da kompresujemo 
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
# 3. Minimalna veličina odgovora (u bajtovima) za koju se isplati raditi kompresiju ~0.5KB
server.compression.min-response-size=500
server.port=8888
